spring:
  application:
    name: catalog-service
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8002

  servlet:
    context-path: /catalog-service

