spring:
  application:
    name: order-service

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
#       ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    # import: optional:configserver:http://localhost:8010
    import: configserver:http://localhost:8010

  cloud:
    config:
      name: ${spring.application.name}, default, application


server:
  port: 8001
  servlet:
    context-path: /order-service



user-service:
  name: USER-SERVICE
  domain-url: http://USER-SERVICE/user-service
  endpoints:
    get-user:
      url: /user-service/users/{userId}

catalog-service:
  name: CATALOG-SERVICE

# zipkin
management:
  tracing:
    sampling:
      probability: 1.0 # send every request to zipkin
