spring:
  application:
    name: order-service

  profiles:
    active: prod

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true

    hibernate:
#       ddl-auto: create
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    # import: optional:configserver:http://localhost:8010
    import: configserver:http://localhost:8010

  cloud:
    config:
      name: ${spring.application.name}-${spring.profiles.active}, default, application


user-service:
  name: USER-SERVICE
  endpoints:
    get-user:
      url: /user-service/users/{userId}