server:
  port: 8011

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8010"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowercase-service-id: true
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE-MS
          predicates:
            - Path=/order-service/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
        - id: CATALOG-SERVICE
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**

services:
  - catalog-service
  - order-service

app-config:
  name: API-GATEWAY

  service-details:
    - name: ORDER-SERVICE
      url: http://user-service.localhost.com
    - name: USER-SERVICE
      url: http://user-service.localhost.com